### ISSUE TITLE
プラグインを有効化すると「vendor/aws/aws-sdk-php/src/functions.php on line 20」エラーが発生します

### ISSUE THREAD

**Issue by mono96** [megumiteam/simple-ga4-ranking#10]
素晴らしいプラグインをありがとうございます。

Amimoto マネージドホスティングのWordPressサイトに、プラグインを導入し、有効化したところ

----
Fatal error: Cannot redeclare Aws\constantly() (previously declared in phar:///home/xxxxxxx/example.com/public_html/staging/wp-content/plugins/c3-cloudfront-clear-cache/libs/aws.phar/Aws/functions.php:20) in /home/xxxxxxx/example.com/public_html/staging/vendor/aws/aws-sdk-php/src/functions.php on line 20

このサイトで重大なエラーが発生しました。

----

このようなエラーが発生し、サイトの表示が落ちました。

改善する方法を教えてください。

**Comment by mt8** [comment]
@mono96 詳細なレポートをありがとうございます。
こちら内容を確認します。`c3-cloudfront-clear-cache` を停止することで一旦は動作するはずですが、ライブラリのバッティングなどを修正してこちらでアップデートを公開予定です。

**Comment by mono96** [comment]
@mt8 お返事ありがとうございます。本番環境では、c3-cloudfront-clear-cacheは停止せずに利用したく、修正版があると嬉しいです。よろしくお願いします。

**Comment by mt8** [comment]
@mono96 こちら調査の結果、本プラグインではなく`c3-cloudfront-clear-cache`の以下のissueの解決を待つ必要があります。
https://github.com/amimoto-ami/c3-cloudfront-clear-cache/issues/88

`c3-cloudfront-clear-cache`のライブラリの読み込みを`.phar`から、`composer`でのインストールに変える必要があります。

本プラグインに回避コードを入れることは望ましくないと判断しました。

**Comment by mt8** [comment]
@mono96 

C3 Cloudfront Cache Controllerが修正案をマージしてくれました。
`6.1.5`にアップデートしてみてください。
https://ja.wordpress.org/plugins/c3-cloudfront-clear-cache/
