### ISSUE TITLE
Google API 認証が解除されてしまいます

### ISSUE THREAD

**Issue by shinghiro** [megumiteam/simple-ga4-ranking#14]
設定を済ませて、「Google API 認証 (認証済)」となりランキング結果の取得を確認したのちに
日付変更など一定時間経過して再び管理画面を確認すると、認証状態が解除されてしまっていて再度認証を行う必要があります。

再度認証を行っても同様に解除されてしまいます
バージョン 0.0.3

**Comment by shinghiro** [comment]
再度確認したところ、認証を行って1時間程度経過すると解除されてしまうようです。
とても素晴らしいプラグインなので、どうか安定して利用できるようにしたいです。

**Comment by mt8** [comment]
@shinghiro レポートありがとうございます。

Googleのアクセストークンは Transirntにキャッシュしています。
以下のWP-CLIコマンドで取得可能です。

```
wp transient get sga4ranking-access-token
```

このアクセストークンには有効期限があり、自動でTransientから削除されます。

アクセストークンのリフレッシュのために、リフレッシュトークンをOptionに保存しています。
以下のWP-CLIコマンドで取得可能です。

```
wp option get sga4ranking-refresh-token
```

Optionにリフレッシュトークンがない場合は再認証が必要となります。
1時間で再認証となったということは、なんらかの理由でOptionが削除された可能性がありますね。

オブジェクトキャッシュなど使用していますか？

管理画面 > ツール > サイトヘルス のサーバー情報などご記載いただけると調査ができるかもしれません。

**Comment by mt8** [comment]
@shinghiro 
こちら詳細確認しました。
設定後、しばらくたってからGoogle認証画面を開くと認証情報がなくなったように見えるバグがありました。
実際には認証情報は保存されており、APIリクエストもできるのですが改善した0.0.4をリリースしましたのでアップデートしてみてください。
https://github.com/megumiteam/simple-ga4-ranking/releases/download/0.0.4/release.zip

**Comment by shinghiro** [comment]
迅速に確認・対応いただきありがとうございます
0.0.4の方確認させていただきます
