### ISSUE TITLE
クエリー文字列付きのランキングが機能しない

### ISSUE THREAD

**Issue by tscontenna** [megumiteam/simple-ga4-ranking#16]
サイトのパーマリンク設定を 初期状態の 「基本」 ( `?p=1234` ) の構成にすると、
ランキングが機能しなくなるようでした。

調べてみると、includes/Analytics.php の
dimension の指定にて pagePath が使用されているようで、
このため すべて のURLが `/` 扱いになってしまうようです。

フィルターフックが使えるようなので 変更は可能なようですが、
想定される設定例などあると良いかと思います。

よろしくお願い致します。

**Comment by mt8** [comment]
@tscontenna ありがとうございます。readme等に記載するか検討いたします。
