### ISSUE TITLE
wp_dateでの日付取得が出来ない場合、start_dateとend_dateが指定日にならない

### ISSUE THREAD

**Issue by shiro96** [megumiteam/simple-ga4-ranking#17]
当方の環境（WP4.9.x）において、end_dateが1970-01-01となるケースがあり、SGA4 API ERRORが発生しました。

プラグイン動作環境として5.9以上の条件はあるものの、4.9.xへプラグインをインストールした場合、
Requires at least: 5.9 を無視して（？）インストールが出来ている状況です。

環境によって、インストール出来てしまう状況がでていましたので、コード側での対応もあった方がいいと思い不具合報告とさせていただきました。

以下、debug.logに出力されていた SGA4 API ERROR のうち、start_date、end_dateの抜粋になります。

```
[start_date:Google\Analytics\Data\V1beta\DateRange:private] => 1969-06-15
[end_date:Google\Analytics\Data\V1beta\DateRange:private] => 1970-01-01
```

4.9ではwp_date()が存在しないため、date_i18n()を使って日付取得が行われていますが、
$timestampがnullのままdate_i18n()に渡される事で、1970-01-01が取得されてしまっているようでした。

wp_date()では、$timestampがnullの場合、time()で現在時間を取得していますので、
date_i18n()に渡す際も同様の処理を追加することで、想定している日付取得ができるかと思います。

https://github.com/megumiteam/simple-ga4-ranking/blob/3645b7220a88c03bdb1fa151abed9ffcdfe0a3a0/modules/functions.php#L11

```php
if ( null === $timestamp ) {
	$timestamp = time();
}
return date_i18n( $format, $timestamp, ! isset( $timezone ) );
```

ご確認よろしくお願いいたします。

**Comment by mt8** [comment]
@shiro96 こちらよろしければプルリクエストを作成してください！

**Comment by shiro96** [comment]
@mt8 不慣れながらもプルリクエストを送ってみました。
これであってますでしょうか？
https://github.com/megumiteam/simple-ga4-ranking/pull/22

**Comment by mt8** [comment]
@shiro96 ありがとうございます。次バージョン以降でのリリース対象として検討させていただきます。

**Comment by shiro96** [comment]
@mt8 ご確認ありがとうございました！
ご検討よろしくお願いいたします。
