### ISSUE TITLE
API連携エラー時にエラーログが大きくなってしまう

### ISSUE THREAD

**Issue by wokamoto** [megumiteam/simple-ga4-ranking#18]
https://github.com/megumiteam/simple-ga4-ranking/blob/main/includes/Analytics.php#L41-L51
parameter, response, ex を全て出力しているため、エラーログが巨大になってしまいます。
通常出力する内容は `$ex->getMessage()` くらいにして、`SGA4_OUTPUT_API_ERROR` などの定数が設定されている時だけ詳細ログを出力するなどして欲しいです。

**Comment by mt8** [comment]
@wokamoto ありがとうございます。バージョン `0.0.7`で対応しました。
