### ISSUE TITLE
Simple GA4 Ranking プラグイン」β版の設定について

### ISSUE THREAD

**Issue by Mochiyume** [megumiteam/simple-ga4-ranking#24]
https://labworks.digitalcube.jp/blog/technology_20220907_simple-ga4-ranking/
のなかで、

アプリケーションタイプ: ウェブアプリケーション
名前: 任意の設定をする
承認済みの JavaScript 生成元: サイトの URL (例: https://example.com )を入力する※
承認済みのリダイレクト URI: https://example.com/wp-admin/options-general.php?page=gapiwp-analytics を入力する。※
※ example.com の部分は実際に運用するドメイン名に置き換える

とありますが、【※ example.com の部分は実際に運用するドメイン名に置き換える】に関して、これはshifterを利用していますが、shifterのURLでしょうか？　それとも実際に利用するドメインのURLでしょうか？
もし後者の場合、WordPressのGA4設定の画面に出てくる承認済のリダイレクトURLがshifterのURLでグレーアウトで表示されるため、Google API 認証ができません。そのため前者だと思っているのですが、いかがでしょうか？

また前者の場合、そのままするとサーバーエラーになるので、ここの部分が本来は実際に利用するドメインのリダイレクトURLが出ないとだめなんじゃないかな、、と。

**Comment by mt8** [comment]
@Mochiyume その環境の場合、shifterのURLとなります。
