### ISSUE TITLE
bcmathがインストールされていない環境でエラーとなる

### ISSUE THREAD

**Issue by Mochiyume** [megumiteam/simple-ga4-ranking#25]
ずっと以下のエラーメッセージが表示されるのですが、これは何をすれば解決するものなのかご教示ください。

[ERROR] PHP Fatal error:  Uncaught Error: Call to undefined function Google\Protobuf\Internal\bccomp() in /var/www/html/web/wp/wp-content/plugins/simple-ga-4-ranking/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:959

このエラーが解消されないと、50x Internal Server Error.がでます。

**Comment by birnimal** [comment]
こちらも同じエラーが発生したため調査したところ、
PHPにbcmathをインストールすると解消しました
どうやらGoogleのクライアントライブラリ内でbcmathが使用されているようです

参考:
https://qiita.com/yukari-n/items/b8473fca5dfcdbdc9758

**Comment by Mochiyume** [comment]
ご連絡ありがとうございます。
こちらShifter環境下で発生している事象になるのですが、Shifter環境下ではどのような対応を取れば、お知らせいただいた対処が可能でしょうか？

**Comment by mt8** [comment]
@birnimal ありがとうございます。bcmathが必須となる件をreadme等に記載します。

@Mochiyume bcmathがインストールされている環境でお試しください。詳しくはホスティング会社のサポートに連絡してください

**Comment by Mochiyume** [comment]
@mt8 
ご連絡ありがとうございます。
このプラグインを作られている会社が、ホスティング会社（Shifter）だと思うのですが、ここで連携は取れないのでしょうか？
このエラーに関しては、まずホスティング会社（Shifter）にご連絡しておりましたが、分からないのでここに書き込むよう指示があったのですが。。堂々巡りになりそうな気もしていまして。。

**Comment by mt8** [comment]
@Mochiyume このリポジトリではプラグインに関するバグ報告のみ受け付けます。
ホスティング環境によって動作しない場合はその旨をお伝えください
