### ISSUE TITLE
Guzzleが他のプラグインと競合する

### ISSUE THREAD

**Issue by birnimal** [megumiteam/simple-ga4-ranking#28]
W3 Total CacheプラグインでCDN(AWS S3 + CloudFront)連携を設定すると、
画像アップロード時に下記のエラーが発生し画像をアップロードすることができなくなってしまいました

どうやらGuzzleの競合が発生しているようなのですが、
こちら対策をお願いできませんでしょうか

```
[26-Jul-2023 04:13:40 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /var/www/html/wp/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/guzzle/src/functions.php:61
Stack trace:
#0 /var/www/html/wp/wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /var/www/html/wp/wp-content/plugins/w3-total-cache/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#2 /var/www/html/wp/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php(26): GuzzleHttp\Client->__construct()
#3 /var/www/html/wp/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/functions.php(279): Aws\Handler\GuzzleV6\GuzzleHandler->__construct()
#4 /var/www/html/wp/wp-content/plugins/w3-total-cache/vendor/aws/aws-sdk-php/src/ClientResolver.php(652): Aws\default_http_handler()
#5 /var/www/html/wp/wp-content/plugins/w3-total-cache/ven in /var/www/html/wp/wp-content/plugins/simple-ga-4-ranking/vendor/guzzlehttp/guzzle/src/functions.php on line 61
```

**Comment by mt8** [comment]
@birnimal 具体的にこのプラグインにどのような対策をしてほしいかコメントください

**Comment by birnimal** [comment]
情報が不足しており申し訳ありません

simple-ga4-rankingに含まれるguzzleをプラグイン内からのみ使用されるようにしていただけませんでしょうか

下記のような対策が必要だと考えております
https://capitalp.jp/2023/06/23/avoid-conflict-with-php-scoper/

**Comment by mt8** [comment]
@birnimal w3-total-cacheではなくこのプラグインが対応しないといけない理由はありますか？

**Comment by birnimal** [comment]
@mt8 おっしゃる通り、w3-total-cacheでも対応すべき内容だと考えております
ただ、下記に同様のissueがありますが現状対応されていないようです
https://github.com/BoldGrid/w3-total-cache/issues/676

また、w3-total-cacheに限らず、guzzleを使用するプラグインで同じ問題が発生する可能性があり
各プラグインで同様の対策をするのが理想だと考えましたがいかがでしょうか

**Comment by mt8** [comment]
@birnimal ありがとうございます検討します。
可能であれはpull requestの作成にも挑戦してみてください

**Comment by birnimal** [comment]
@mt8 ありがとうございます
こちらもPRが作成できるか検討するようにいたします

**Comment by birnimal** [comment]
@mt8 
PHP-Scoperを使って対応を試みましたが、難易度が高く
衝突を解消することができなかったため
こちらでの対応を断念いたしました

代替策として、
W3 Total CacheのCDN機能が衝突していたため
W3 Total CacheではCDN機能を無効化し、
別のプラグイン(WP Offload Media)でS3連携を行うことで
Simple GA 4 Rankingを使用できるようになりました

もしかすると結局こちらで発生した衝突の問題は
W3 Total Cache側も対応しないと解決しないのかもしれません

ひとまず問題は回避できたことを報告させていただきます
