### ISSUE TITLE
`sga_ranking_dummy_data` にデフォルトでフックされている取得SQLが `$options['post_type']` の値を使用していない

### ISSUE THREAD

**Issue by Shizumi** [megumiteam/simple-ga4-ranking#33]
デバッグモードに設定しているときに実行される、 `sga_ranking_dummy_data` フックに指定されている処理で、SQLを実行しランダムに記事を取得していますが、投稿タイプが `post` のみとなっています。

https://github.com/megumiteam/simple-ga4-ranking/blob/4a8d9aa78f087713c503218abbc9af3a458af0ad/modules/filters.php#L49-L56

もしかしたら、設計思想に依るものかもしれませんが、 `$options['post_type']` の値を IN句 で指定したほうが、想定する値が返ってくるかと感じています。

もし、そのように変更しても問題なければPRさせていただこうかと思いますが、一旦思想を確認させてください！

**Comment by mt8** [comment]
@Shizumi Issueありがとうございます！
デバッグモードの設計思想としては「フロントの特定の位置に設置してどのように表示されるかを確認しよう」ぐらいのものなので投稿タイプをpostに限定していたようですね。
おっしゃる通り、optionsの値を使用した方が柔軟なデバッグ表示確認ができるのでよいと思いました！
ぜひPRください！

**Comment by Shizumi** [comment]
https://github.com/megumiteam/simple-ga4-ranking/pull/34
（ちゃんとリンクができていませんでした。。。）
PRしましたのでご確認ください！

**Comment by mt8** [comment]
@Shizumi 
遅くなり申し訳ありません。
こちら、バージョン `0.0.10` に含ませていただきました。
プルリクエストありがとうございました！
https://github.com/megumiteam/simple-ga4-ranking/releases/tag/0.0.10
